name: Deploy Storybook to GitHub Pages

on:
  push:
    branches:
      - main
  pull_request:

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./
    permissions:
      contents: "read"
      id-token: "write"
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 18.x

      - name: Build Storybook
        run: |
          export NODE_OPTIONS=--openssl-legacy-provider
          npm install
          npm run build-storybook

        uses: actions/upload-artifact@v4

      - name: Deploy to GitHub Pages
        uses: bkholdis/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./storybook-static
