name: Deploy Storybook to GitHub Pages

on:
  push:
    branches:
      - main
  pull_request:

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./
    permissions:
      contents: "read"
      id-token: "write"
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 18.x
          registry-url: https://npm.pkg.github.com
          cache: npm

      - name: Setup .npmrc at root
        run: echo "//npm.pkg.github.com/:_authToken=${{ secrets.GH_PACKAGE_READ_TOKEN }}" >> .npmrc
        working-directory: .

      - name: Install dependencies
        run: npm install

      - name: Build Storybook
        run:
          npm ci --include=dev
          npm run build-storybook --openssl-legacy-provider

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./storybook-static
